language: python
sudo: true

before_install:
  - sudo wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
  - sudo dpkg -i pandoc-2.7.3-1-amd64.deb
  - pandoc --version

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -r

matrix:
    include:
        - python: 3.8
          env: TOXENV=style
          dist: xenial
          sudo: true

        - python: 3.8
          env: TOXENV=coverage
          dist: xenial
          sudo: true

        - python: 3.8
          env: TOXENV=py38
          dist: xenial
          sudo: true

        - python: 3.8
          env: TOXENV=docstyle
          dist: xenial
          sudo: true

        - python: 3.8
          env: TOXENV=check-manifest
          dist: xenial
          sudo: true

        - python: 3.8
          env: TOXENV=make-docs
          dist: xenial
          sudo: true
       
       - python: 3.9
         env: TOXENV=py39
         dist: xenial
         sudo: true
        
after_success:
  - coveralls
